from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from datetime import datetime
import os


def create_complaint_pdf(data, info, formal_complaint, complaint_id):
    os.makedirs("generated_docs", exist_ok=True)

    file_path = (
    f"generated_docs/{complaint_id}.pdf"
)

    doc = SimpleDocTemplate(file_path)

    styles = getSampleStyleSheet()

    story = []

    # ==========================================
    # HEADER
    # ==========================================

    story.append(
        Paragraph("CITIZEN GRIEVANCE MANAGEMENT SYSTEM", styles["Title"])
    )

    story.append(
        Paragraph("Official Complaint Report", styles["Heading2"])
    )

    story.append(Spacer(1, 15))

    # ==========================================
    # COMPLAINT DETAILS
    # ==========================================

    story.append(
        Paragraph("<b>COMPLAINT DETAILS</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(f"<b>Complaint ID:</b> {complaint_id}", styles["Normal"])
    )

    story.append(
        Paragraph(
            f"<b>Generated On:</b> {datetime.now().strftime('%d-%m-%Y %H:%M')}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph("<b>Status:</b> PENDING", styles["Normal"])
    )

    story.append(Spacer(1, 12))

    # ==========================================
    # CITIZEN DETAILS
    # ==========================================

    story.append(
        Paragraph("<b>CITIZEN DETAILS</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(f"<b>Citizen Name:</b> {data['name']}", styles["Normal"])
    )

    story.append(
        Paragraph(f"<b>Department:</b> {info['department']}", styles["Normal"])
    )

    story.append(
        Paragraph(f"<b>Category:</b> {info['category']}", styles["Normal"])
    )

    story.append(
        Paragraph(f"<b>Priority:</b> {info['priority']}", styles["Normal"])
    )

    story.append(Spacer(1, 12))

    # ==========================================
    # LOCATION DETAILS
    # ==========================================

    story.append(
        Paragraph("<b>LOCATION DETAILS</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(f"<b>Landmark:</b> {data['typed_location']}", styles["Normal"])
    )

    story.append(
        Paragraph(f"<b>Resolved Address:</b> {data['resolved_address']}", styles["Normal"])
    )

    story.append(
        Paragraph(f"<b>Latitude:</b> {data['latitude']}", styles["Normal"])
    )

    story.append(
        Paragraph(f"<b>Longitude:</b> {data['longitude']}", styles["Normal"])
    )

    story.append(Spacer(1, 12))

    # ==========================================
    # ORIGINAL COMPLAINT
    # ==========================================

    story.append(
        Paragraph("<b>ORIGINAL COMPLAINT</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(data["complaint"], styles["BodyText"])
    )

    story.append(Spacer(1, 12))

    # ==========================================
    # FORMAL COMPLAINT LETTER
    # ==========================================

    story.append(
        Paragraph("<b>FORMAL COMPLAINT LETTER</b>", styles["Heading2"])
    )

    formatted_complaint = formal_complaint.replace("\n", "<br/>")

    story.append(
        Paragraph(formatted_complaint, styles["BodyText"])
    )

    story.append(Spacer(1, 12))

    # ==========================================
    # SYSTEM INFORMATION
    # ==========================================

    story.append(
        Paragraph("<b>SYSTEM INFORMATION</b>", styles["Heading2"])
    )

    story.append(
        Paragraph("Generated By: AI Complaint Generator", styles["Normal"])
    )

    story.append(
        Paragraph(
            f"District: {data['resolved_address'].split(',')[0]}",
            styles["Normal"]
        )
    )

    doc.build(story)

    return file_path